# With help from https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
version: '3.5'

services:

    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
            POSTGRES_HOST_AUTH_METHOD: trust
            # PGDATA: /data/postgres
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
        ports:
            - 5432:5432
        networks:
            - postgres

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@upload.farm}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
           - pgadmin:/root/.pgadmin
        ports:
          - "${PGADMIN_PORT:-5050}:80"
        networks:
          - postgres
        restart: unless-stopped

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
          - postgres

    webapp:
        container_name: webapp
        restart: always
        image: joserc87/sdv-summary:latest
        depends_on:
            - "postgres"
        ports:
            - 5000:5000
        volumes:
            - ./sdv/assets:/app/sdv/assets
        networks:
          - postgres
        environment:
            PYTHONPATH: .:sdv
            # FLASK_APP: ./runserver.py
            FLASK_RUN_HOST: 0.0.0.0


networks:
  postgres:
    driver: bridge

volumes:
    db-data:
    pgadmin:
