FROM python:3.7-slim

WORKDIR /app
ENV PYTHONPATH: .:sdv

# libz and libjpeg are needed for pillow (PIL)
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    libz-dev \
    libjpeg-dev

COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

# Clean some space
RUN apt-get autoremove -y gcc

COPY . /app

CMD [ "gunicorn", "-c", "gunicorn_config.py", "sdv:app"]
